sudo: false
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '6'
script: bash ./scripts/deployToGHPages.sh
notifications:
  email: false
  slack:
    secure: dZ1kj80MQSGJzJZQKZCDehYQoIS0qBajafvI7Jc1Z2OQTxyx2sLezJxeh3S0eJ/2wLrL/o/UDLcqepTCDLZhsgh0subAwnzpaT2O1k1OZydF682Jxmq6cZLFy7WEPsqFbA3mMvx+HyqTjtIF7YyWkXI6GPlB2RbLSquuUIbUrc8lKHCpHIZlqM4aSmLd/baiL8p53XlEo/+Qe+31eR39iKnnN+90kqIY1prth3rUi1REVXFvoz5M9uNY7lq8wS+pSLWVHeahtXOeJfET05Rzt3BDky3Xt+PHpincDxH8cH364vxXqsp6q07GbSmqYn2GO3mPCT2DHuoqPymAqkqJCd3MOzblcgOtJ0k8KhqF6EgMI/+33V25DsKtBGph6qVdUPuYv0EPKda+HpcbHG35R/334EtK4LxHONs1ArLyCW0xHyk53hEnT4X2SkG0aA/BYubv7fnS+BoBO1bZpQE6CZB0DxKy9pzxva2r/e6/F+tnplRoZ64T6VXd1jIUHfIbtv1Rjrkhq4xkiglGdO18lGFxj/VaLTtsEWxNNB6uL48LAowGSQ7FNESMu4xsRWVMA+kYwMTZbws9x6pnSBpeHCIC7hSvNX+b32iPd5Jqo0xbV5uvXsd9YreqAe+zK91r8WjZeQ4JJfYzCwh9R4ivDfTuaiZOUCyEr7Arxav6Sfc=
