sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '6'
script: bash ./scripts/deployToGHPages.sh
notifications:
  email: never
  slack:
    secure: SBoL+RriWbwbCyrtNaK9qoNzIs+buDQRQSioPs+83d9wTMV7M4hIWyBvORZaQdA/l2mXQYlE6MPVo4TaXlNuryRLxc/ZPwgLsyThH10YTf75buoNWVSP8UP7XjdvAQyyvKAsRuI/cIt1rpu2VFG37CRs072gkDrF8CTX7naJocXEZvwJKKYzcO0R+Y8jjh+nL49/lDqmdodUQqYbqVVT1BOLK/W1G0r/HJ4rGGtLsAQI+R9mosEb6vcT0bg54hdCFRJ1AiYu1r3KzaiABYaVF6mllHr4hK6eED4Crm7z6TqqI/GAyGdAw5KYv1AF13WvjeysFMmYuwJ8WrcZRoaLlUFsDO99HM3XUDoT7gTBuKdb7S3NlhFM5Hxrlg7Z/Bj6ikDM5tYcszadTbBVILFZl0uo+iN2zBkoX4dzKCK1MpDpY22/uezFgicF9MneK1cWuRjQG/luxqu5f/6xf8avc9QJMKJ2Bhh8/nhSwOWXjVP/YTdRbm4lWxT+bkPXTd9DJ4+OSCzlgOZzT5PlUZyNA/TJuC3715ONQUWHgPqQlM0umviLgo1OQTqnc7N7oxqURYa24gL9JC0qcWrRBcFvoQ0xVeI6IX5Mrw/jWx/njpwbnAST7CyRufYsjv8ObJ13MUFJVuzSFtbjaX12JpK93Dv/cyxx+87TgevlbSs3XBY=
