sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '6'
script: bash ./scripts/deployToGHPages.sh
notifications:
  email: 
    - sen@legendofcode.com
  slack:
    secure: sWAXy0i25SL1R0Tmt6e7qODvi9kTbbSvOPtcYUGwLsxxp/DmnmIE2Y1dZoQdJx7i+4RM/lXDBJawtxiz9T8z9O4ArdqyzH7u7dJx8eOQTaNsrcnx1z0Vp4Ig9nZZGUqOI05T9QaLn2LMC9XSDBNs6T6/eMOb7sk7N7JpMv+4R2dYtZ5IafNp81FaBvr+YuCJDTqo1Dd0YYvL333rEreYAWSBSagH/OdYigiYW1jeqU2eIVIJbDWRXqgRNKe8hOzIvOJN/oz4Rf0ZacL178Mf9sprWao24yIDdky4/bchDCLzYQ5097S0gR6IH43ScPAdFQYg5+lm54zlmIYCbv6jAgTMnqK7quIfH6yhIQJ9ZtJQqYSv3iYGZ+fHoYrpoewCCWpCtuf5yvp2PwnYZtZev9gxIFMmFTCcoamGPTInnEJu63UBOE+FJAFolCvaOZrTF2CZFLmUPLpEyNibrnFro/wYmqwNztRwx6onFhcT747ZSwR5sS9UgxFhisGhSh6y+bpfH+lk61U+v2SafBeo6Lwj9wYOKWXqKhoV1V0gcRHMOJPVP4K9LW1IE0d3DG7SZSR2vBznUiqGjRwhJssahNemIvN4PKoj/o8UOk66ns5q9rK3h78sj9i1yUzDcvDJgEqNtL243MR1nghmzCA2pWJ2RKvDBzCU0ojj1xT8p14=
