sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '6'
script: bash ./scripts/deployToGHPages.sh
notifications:
  email: never
  slack:
    secure: opVxokbZ/niuyDKzQYWwnUacjFeVHClf6crNWRPsYXYqPovKcTk6NglHLYU9UTi7/u/8C1KoAvyE+sOxqHZBO4GWIX53ElVj5QJlh2bVId7AfjAnSA9qdu2fX2ZAigCKZ6Q3VRhI/QavXfPpjyClkOUGLkIv/IzdMPJA94/zf78QV3r3diOxP11myDjPN4UcXXlspYfMn55GC0s3m+jSvpah3nnICtbbAVSKDtQKLbmHInHQjDhVD/28XqbWaD18wbAh1ARDNtxxqB9wwBSZVq/smqBPo3+0ZGUACynK2exPRj29dTwS/0XkCRdIKIUS8F1w9FLm7Z2LzPKVYF9z7O/OVwY8lo3/O3FR9PW6NGY/zqZNpeaJPuePVAPbSyQih98lAcj9sC/GuQkHuhS7HiQDhh2Z7HgGlg9oYIXv4I+6VqRpqkSaL3mwC5I6+ucLBXBO8AXJwK8apl9/lYOftMzE4cd8sKrqbbHE0shmve56vBxSD9k6opGZjQ4OHBhoNAGAlpCb3PLLj1ugcSOqC5Jk3IpY3YyGSky+AiBfzLVW8D34uFHAw49O2jibGUkBle1p6uLPf/UUPBLrwuAzAM46K+9q5aVD4DAtpVi/+7FoRR+SE4Ib76jLj5M3YD5d8lcK6Cr5xto3EGyXy4bB241Wo+sqbvP8vmVCIah3uvU=
